### ISSUE TITLE
Error building on Alpine Linux aarch64 - missing x86intrin.h: No such file or directory

### ISSUE THREAD

**Issue by cybern0id** [Chia-Network/chiavdf#127]
I'm trying to build chia-blockchain on an arm64 Alpine Linux VM and it is failing at the chiavdf wheel step. I get the same error if I try to build chiavdf independently of the chia-blockchain repo too.

I understand that I can disable the VDF client build in chia-blockchain by using a compile-time environment variable (and this is confirmed working for me), as explained in the [Chia github Wiki](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#other-install-methods-and-environments) which mentions the VDF client Timelord components being not so cross-platform friendly however, the chiavdf [README](https://github.com/Chia-Network/chiavdf/blob/main/README.md) mentions "The primary build process for this repository is to use GitHub Actions to build binary wheels for MacOS, Linux (x64 **and aarch64**), and Windows and publish them with a source wheel on PyPi...."

I'm not sure whether this is due to a bug or due to the build process not detecting my architecture and environment correctly and therefore failing to ignore/bypass/substitute the include of the x86intrin.h header file, or is expected behaviour due to aarch64 support being a work in progress? Or perhaps I'm missing a system dependency?

Platform details:

```
(venv) alpine:~$ gcc --version
gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(venv) alpine:~$ g++ --version
g++ (Alpine 10.3.1_git20211027) 10.3.1 20211027
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(venv) alpine:~$ cmake --version
cmake version 3.21.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

(venv) alpine:~$ cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)

(venv) alpine:~$ rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)

(venv) alpine:~$ pip --version
pip 22.2.2 from /home/user/sources/chia-blockchain/venv/lib/python3.9/site-packages/pip (python 3.9)

(venv) alpine:~$ apk list --installed | grep gmp
libgmpxx-6.2.1-r1 aarch64 {gmp} (LGPL-3.0-or-later OR GPL-2.0-or-later) [installed]
gmp-6.2.1-r1 aarch64 {gmp} (LGPL-3.0-or-later OR GPL-2.0-or-later) [installed]
gmp-dev-6.2.1-r1 aarch64 {gmp} (LGPL-3.0-or-later OR GPL-2.0-or-later) [installed]

(venv) alpine:~$ apk list --installed | grep boost
boost1.77-atomic-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-program_options-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-iostreams-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost-dev-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-date_time-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-graph-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-math-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-random-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-json-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-wave-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-chrono-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-libs-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-prg_exec_monitor-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-nowide-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-unit_test_framework-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-context-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-stacktrace_basic-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-container-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-thread-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-fiber-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-wserialization-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-dev-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-serialization-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-filesystem-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-type_erasure-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-contract-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-log_setup-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-timer-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-stacktrace_noop-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-locale-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-log-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-regex-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-coroutine-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-system-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
boost1.77-python3-1.77.0-r1 aarch64 {boost1.77} (BSL-1.0) [installed]
```

Build details:

```
git clone https://github.com/Chia-Network/chia-blockchain.git --branch latest
cd chia-blockchain
python3 -m venv venv
. ./venv/bin/activate
pip install --upgrade pip
bash install.sh
```

Debug output snippet (this is for chia-blockchain main repo but exactly the same error occurs when trying latest/1.5.1):
```
Building wheels for collected packages: chia-blockchain, chiavdf
  Building editable for chia-blockchain (pyproject.toml) ... done
  Created wheel for chia-blockchain: filename=chia_blockchain-1.5.2.dev2453-0.editable-py3-none-any.whl size=9471 sha256=662dcba09a50e6735c174ff64c1040ae4415a69fd05457d12d51ed433def88c8
  Stored in directory: /tmp/pip-ephem-wheel-cache-h534dyig/wheels/92/aa/d1/da406d5de1291dd5b00b242bbd4735d00778842e91d628c3b6
  Building wheel for chiavdf (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for chiavdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      running bdist_wheel
      running build
      /tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/command/build.py:31: SetuptoolsDeprecationWarning:
                  It seems that you are using `distutils.command.build` to add
                  new subcommands. Using `distutils` directly is considered deprecated,
                  please use `setuptools.command.build`.

        warnings.warn(msg, SetuptoolsDeprecationWarning)
      running build_ext
      -- The C compiler identification is GNU 10.3.1
      -- The CXX compiler identification is GNU 10.3.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      GMP_INCLUDES=/usr/include
      -- Found GMP: /usr/include (Required is at least version "5.1.0")
      GMP_INCLUDES=/usr/include
      -- Found GMPXX: /usr/lib/libgmpxx.so
      -- pybind11 v2.6.2
      -- Found PythonInterp: /home/user/sources/chia-blockchain/venv/bin/python (found version "3.9.13")
      -- Found PythonLibs: /usr/lib/libpython3.9.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-nk_d3eym/chiavdf_cd2fd4e435de4e7db3bd697de5a50417
      [ 16%] Building CXX object CMakeFiles/verifier_test.dir/verifier_test.cpp.o
      [ 33%] Building CXX object CMakeFiles/chiavdf.dir/python_bindings/fastvdf.cpp.o
      [ 50%] Building C object CMakeFiles/verifier_test.dir/refcode/lzcnt.c.o
      [ 66%] Building C object CMakeFiles/chiavdf.dir/refcode/lzcnt.c.o
      [ 83%] Linking CXX executable verifier_test
      [ 83%] Built target verifier_test
      [100%] Linking CXX shared module build/lib.linux-aarch64-cpython-39/chiavdf.cpython-39-aarch64-linux-musl.so
      [100%] Built target chiavdf
      running build_hook
      In file included from vdf_client.cpp:2:
      vdf.h:6:10: fatal error: x86intrin.h: No such file or directory
          6 | #include <x86intrin.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      make: *** [<builtin>: vdf_client.o] Error 1
      Traceback (most recent call last):
        File "/home/user/sources/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/user/sources/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/sources/chia-blockchain/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 266, in <module>
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-u8jv1kik/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "<string>", line 44, in run
        File "<string>", line 76, in invoke_make
        File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'make -C src -f Makefile.vdf-client' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chiavdf
Successfully built chia-blockchain
Failed to build chiavdf
ERROR: Could not build wheels for chiavdf, which is required to install pyproject.toml-based projects
```

**Comment by hoffmang9** [comment]
vdf_client (timelording) isn’t supported on ARM 64 yet and probably will not be. The flag is used to restrict the VDF library to proof checking only on most platforms. With the pending arrival of ASIC vdf_client, ARM 64 hosts will be added to support that hardware.

**Comment by cybern0id** [comment]
Great, thanks @hoffmang9 for clarification and apologies for the noise. I'll close this.
