### ISSUE TITLE
Bluebox/sanitizer crash

### ISSUE THREAD

**Issue by hoffmang9** [Chia-Network/chiavdf#31]
Was running 10 vdf_clients in sanitize mode on benstl.chia.net and fullnode threw this error and timelord stopped doing anything:
```
17:37:33.910 full_node root                    : ERROR    unhandled mapping function <function partial_async.<locals>.inner at 0x7f46c3446af0> worker exception on (<StreamReader eof transport=<asyncio.sslproto._SSLProtocolTransport object at 0x7f46a7dbe880>>, <StreamWriter transport=<asyncio.sslproto._SSLProtocolTransport object at 0x7f46a7dbe880> reader=<StreamReader eof transport=<asyncio.sslproto._SSLProtocolTransport object at 0x7f46a7dbe880>>>, None, True, False)
Traceback (most recent call last):
  File "/home/hoffmang/chia-blockchain/venv/lib/python3.8/site-packages/aiter/simple_map_aiter.py", line 27, in simple_map_aiter
    yield await _map_f(_)
  File "/home/hoffmang/chia-blockchain/src/util/partial_func.py", line 21, in inner
    return await f(first_param, *args)
  File "/home/hoffmang/chia-blockchain/src/server/pipeline.py", line 161, in stream_reader_writer_to_connection
    con = ChiaConnection(
  File "/home/hoffmang/chia-blockchain/src/server/connection.py", line 46, in __init__
    self.local_host = socket.getsockname()[0]
AttributeError: 'NoneType' object has no attribute 'getsockname'
```

**Comment by hoffmang9** [comment]
[debug.log](https://github.com/Chia-Network/chiavdf/files/5289261/debug.log)

It seems that timelord stopped launching vdf_clients earlier but I don't see an obvious error.

**Comment by hoffmang9** [comment]
[crash.log](https://github.com/Chia-Network/chiavdf/files/5293982/crash.log)

This was with 0.12.25b

**Comment by hoffmang9** [comment]
And this is a new error running chia-blockchain/master with 0.12.25b0

[crash.log](https://github.com/Chia-Network/chiavdf/files/5294603/crash.log)

**Comment by hoffmang9** [comment]
Full debug log from that run:
[debug.log](https://github.com/Chia-Network/chiavdf/files/5294631/debug.log)

**Comment by hoffmang9** [comment]
vdf_clients do seem to be stopping now however

**Comment by hoffmang9** [comment]
I'm going to resolved this as fixed as it seems that the problem was over in peer gossip.
