### ISSUE TITLE
Execute pip wheel.

### ISSUE THREAD

**Issue by lh232510** [Chia-Network/chiavdf#74]
err log:
Processing /Users/liuhao/Documents/pythonProject/chiavdf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/liuhao/Documents/pythonProject/chiavdf/venv/bin/python3.9 /Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/tmplx6mqoi7
       cwd: /private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-dw9sbrki
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is AppleClang 12.0.0.12000032
  -- The CXX compiler identification is AppleClang 12.0.0.12000032
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=GMP_INCLUDES-NOTFOUND
  CMake Error at /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
    Could NOT find GMP (missing: GMP_INCLUDES GMP_LIBRARIES GMP_VERSION_OK)
    (Required is at least version "5.1.0")
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
    cmake/FindGMP.cmake:74 (find_package_handle_standard_args)
    CMakeLists.txt:17 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-dw9sbrki/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-dw9sbrki/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-i48kintb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-i48kintb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-i48kintb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 266, in <module>
      setup(
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-i48kintb/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-i48kintb/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 112, in run
      self.build_extension(ext)
    File "setup.py", line 139, in build_extension
      subprocess.check_call(["cmake", ext.sourcedir] + cmake_args, env=env)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-dw9sbrki/src', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-dw9sbrki/build/lib.macosx-11-x86_64-3.9', '-DPYTHON_EXECUTABLE=/Users/liuhao/Documents/pythonProject/chiavdf/venv/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Failed to build one or more wheels

**Comment by hoffmang9** [comment]
`export BUILD_VDF_CLIENT=N` and then `pip wheel .`

**Comment by lh232510** [comment]
Still not working, error log:
Processing /Users/liuhao/Documents/pythonProject/chiavdf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: chiavdf
  Building wheel for chiavdf (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/liuhao/Documents/pythonProject/chiavdf/venv/bin/python3.9 /Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/tmp9h8yopt5
       cwd: /private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-y7_bbfq0
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is AppleClang 12.0.0.12000032
  -- The CXX compiler identification is AppleClang 12.0.0.12000032
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  GMP_INCLUDES=GMP_INCLUDES-NOTFOUND
  CMake Error at /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
    Could NOT find GMP (missing: GMP_INCLUDES GMP_LIBRARIES GMP_VERSION_OK)
    (Required is at least version "5.1.0")
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
    cmake/FindGMP.cmake:74 (find_package_handle_standard_args)
    CMakeLists.txt:17 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-y7_bbfq0/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-y7_bbfq0/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/liuhao/Documents/pythonProject/chiavdf/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-18l59bpm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-18l59bpm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-18l59bpm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 266, in <module>
      setup(
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-18l59bpm/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-build-env-18l59bpm/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 112, in run
      self.build_extension(ext)
    File "setup.py", line 139, in build_extension
      subprocess.check_call(["cmake", ext.sourcedir] + cmake_args, env=env)
    File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-y7_bbfq0/src', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/tn/qd5mzld10wv5xz4qp1wz9t040000gn/T/pip-req-build-y7_bbfq0/build/lib.macosx-11-x86_64-3.9', '-DPYTHON_EXECUTABLE=/Users/liuhao/Documents/pythonProject/chiavdf/venv/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for chiavdf
Failed to build chiavdf
ERROR: Failed to build one or more wheels

**Comment by hoffmang9** [comment]
Reading between the lines since you did not tell us what OS...
`brew install gmp`

**Comment by lh232510** [comment]
Sorry for not telling you that my system is my problem. It's solved now, thank you very much!

**Comment by lh232510** [comment]
Is this library used to retrieve spatial proofs?

**Comment by hoffmang9** [comment]
chiavdf is the VDF or Verifiable Delay Function - also known as proof of time.

This is Proof of Space - https://github.com/Chia-Network/chiapos

**Comment by lh232510** [comment]
ok!
